using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Excel = Microsoft.Office.Interop.Excel;

namespace ExcelConvertLib
{
    public class ConstGenerator : BaseGenerator
    {
        const string IniSectionName = "/Script/TACTAN.CommonConstData";

        void WriteCodeHeader(StreamWriter writer, string tablename)
        {
            writer.WriteLine("// automatically generated by the ExcelConverter, do not modify");
            writer.WriteLine(string.Format("// the data is converted from {0}", tablename));
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#include \"CoreMinimal.h\"");
            writer.WriteLine("#include \"CommonConstData.generated.h\"");

            writer.WriteLine();
            writer.WriteLine("UCLASS(config = Game, defaultconfig, meta = (DisplayName = \"Common Const Settings\"))");
            writer.WriteLine("class TACTAN_API UCommonConstData : public UDeveloperSettings");
            writer.WriteLine("{");
            writer.WriteLine("\tGENERATED_BODY()");
            writer.WriteLine("");
            writer.WriteLine("public:");
        }

        void WriteCodeFooter(StreamWriter writer)
        {
            writer.WriteLine("};");
            writer.WriteLine();
            writer.WriteLine("extern TACTAN_API const UCommonConstData* CONST_DATA();");
        }

        void WriteCodeProperty(StreamWriter writer, string sheetName, ref object[,] values)
        {
            writer.WriteLine(string.Format("\t// {0}", sheetName));
            writer.WriteLine();

            int max = values.GetLength(0);
            float fValue = 0.0f;
            int nValue = 0;

            int rowindex = 2;
            long columnCount = 0;

            for (int i = 1; i <= values.GetLongLength(1); ++i)
            {
                string lvalue = Convert.ToString(values[rowindex, i]);

                if (string.IsNullOrEmpty(lvalue))
                    break;

                ++columnCount;
            }
            
            int NumRow = 3;

            while (NumRow <= max)
            {
                sb.Clear();
                Utility.AddTab(sb, 1);

                // 서버에서 묵시적 형변환으로 인한 오류가 발생해서,
                // const convertor 역시 명시적 타입을 사용하도록 수정.
                // 서버에서 발생한 이슈라 클라이언트는 지금 동작을 유지하는 방향으로
                // 민규님과 협의하고 예외처리 해두겠습니다. 참고해주세요.

                string Name = string.Empty;
                string ServerType = string.Empty;
                string Value = string.Empty;
                string Desc = string.Empty;

                switch (columnCount)
                {
                    case 3:
                        Name = Convert.ToString(values[NumRow, 1]).Trim();
                        Value = Convert.ToString(values[NumRow, 2]).Trim();
                        Desc = Convert.ToString(values[NumRow, 3]).Trim();
                        break;
                    case 4:
                        Name = Convert.ToString(values[NumRow, 1]).Trim();
                        ServerType = Convert.ToString(values[NumRow, 2]).Trim();
                        Value = Convert.ToString(values[NumRow, 3]).Trim();
                        Desc = Convert.ToString(values[NumRow, 4]).Trim();
                        break;
                }
                string Type = "FString";

                if (Name.Length > 0)
                {
                    if (Value.Contains("."))
                    {
                        if (Value.EndsWith("f"))
                        {
                            Value = Value.Replace('f', '0');
                        }

                        if (float.TryParse(Value, out fValue))
                        {
                            Type = "float";
                        }
                    }
                    else if (int.TryParse(Value, out nValue))
                    {
                        Type = "int32";
                    }
                    else
                    {
                        string lowerValue = Value.ToLower();
                        if (lowerValue == "true" || lowerValue == "false")
                        {
                            Type = "bool";
                        }
                    }

                    if (Desc.Length > 0)
                    {
                        writer.WriteLine(string.Format("\t// {0}", Desc));
                    }
                    writer.WriteLine("\tUPROPERTY(config, EditAnywhere, BlueprintReadOnly)");
                    writer.WriteLine(string.Format("\t{0} {1};", Type, Name));
                    writer.WriteLine();
                }

                ++NumRow;
            }

            writer.WriteLine(string.Format("\t// {0} end", sheetName));
            writer.WriteLine();
        }

        void WriteCode(StreamWriter writer, string tablename)
        {
            WriteCodeHeader(writer, tablename);

            foreach (Excel.Worksheet ws in MainModule.Inst.GetWorkSheets())
            {
                if (ws == null)
                    continue;

                if (!IsSheetForClient(ws))
                    continue;

                string sheetName = ws.Name;
                object[,] values = (object[,])ws.UsedRange.Value2;

                WriteCodeProperty(writer, sheetName, ref values);
            }

            WriteCodeFooter(writer);
        }

        void WriteConfigProperty(string filename, ref object[,] values)
        {
            string path = Path.GetFullPath(filename);
            int max = values.GetLength(0);

            int rowindex = 2;
            long columnCount = 0;

            for (int i = 1; i <= values.GetLongLength(1); ++i)
            {
                string lvalue = Convert.ToString(values[rowindex, i]);

                if (string.IsNullOrEmpty(lvalue))
                    break;

                ++columnCount;
            }

            int NumRow = 3;
            while (NumRow <= max)
            {
                // 서버에서 묵시적 형변환으로 인한 오류가 발생해서,
                // const convertor 역시 명시적 타입을 사용하도록 수정.
                // 서버에서 발생한 이슈라 클라이언트는 지금 동작을 유지하는 방향으로
                // 민규님과 협의하고 예외처리 해두겠습니다. 참고해주세요.

                string Name = string.Empty;
                string ServerType = string.Empty;
                string Value = string.Empty;
                string Desc = string.Empty;

                switch (columnCount)
                {
                    case 3:
                        Name = Convert.ToString(values[NumRow, 1]).Trim();
                        Value = Convert.ToString(values[NumRow, 2]).Trim();
                        Desc = Convert.ToString(values[NumRow, 3]).Trim();
                        break;
                    case 4:
                        Name = Convert.ToString(values[NumRow, 1]).Trim();
                        ServerType = Convert.ToString(values[NumRow, 2]).Trim();
                        Value = Convert.ToString(values[NumRow, 3]).Trim();
                        Desc = Convert.ToString(values[NumRow, 4]).Trim();
                        break;
                }

                if (Value.Contains(".") && Value.EndsWith("f"))
                {
                    Value = Value.Replace('f', '0');
                }

                if (Name.Length > 0)
                {
                    long result = IniUtility.WritePrivateProfileString(IniSectionName, Name, Value, path);
                }

                ++NumRow;
            }
        }

        void WriteConfig(string filename)
        {
            IniUtility.ClearIniSection(IniSectionName, filename);

            foreach (Excel.Worksheet ws in MainModule.Inst.GetWorkSheets())
            {
                if (ws == null)
                    continue;

                if (!IsSheetForClient(ws))
                    continue;

                string sheetName = ws.Name;
                object[,] values = (object[,])ws.UsedRange.Value2;

                WriteConfigProperty(filename, ref values);
            }
        }

        public static string GetSheetType(Excel.Worksheet ws)
        {
            if (ws == null)
                return string.Empty;

            object[,] values = (object[,])ws.UsedRange.Value2;
            return Convert.ToString(values[1, 1]).Trim();
        }


        bool IsSheetForClient(Excel.Worksheet ws)
        {
            string type = GetSheetType(ws);
            return (type == "common") || (type == "client");
        }

        public bool OnGenerateConst(string constExcel)
        {
            // Code
            string codeOutput = MainModule.Inst.GetClientCodePath("Data/CommonConstData.h");

            if (!MainModule.CheckOutClientCodeFile("Data/CommonConstData.h"))      //perforce check   
            {
                LogSystem.Inst.Add(string.Format("P4Error failed check CommonConstData"));
                return false;
            }

            StreamWriter writer = new StreamWriter(
                     new FileStream(codeOutput, FileMode.Create, FileAccess.ReadWrite), Encoding.UTF8);

            WriteCode(writer, constExcel);

            writer.Flush();
            writer.Close();

            //if (!MainModule.RevertIfUnchangedClientCodeFile("Data/CommonConstData.h"))
            {
                LogSystem.Inst.Add(string.Format("Generate :{0} ", codeOutput));
            }

            // Config
            string inioutput = MainModule.Inst.GetUEPath("Config/DefaultGame.ini");

            if (!MainModule.CheckOutUEFile("Config", "DefaultGame.ini"))      //perforce check   
            {
                LogSystem.Inst.Add(string.Format("P4Error failed check CommonConstData"));
                return false;
            }

            WriteConfig(inioutput);

            LogSystem.Inst.Add(string.Format("Generate :{0} ", inioutput));

            return true;
        }
    }

}
