using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Excel = Microsoft.Office.Interop.Excel;

namespace ExcelConvertLib
{
    public class UEEnumGenerator : BaseGenerator
    {
        void FileHeader(StreamWriter writer)
        {
            DateTime now = DateTime.Now;
            writer.WriteLine("////////////////////////////////////////////");
            writer.WriteLine(string.Format("//automatically generated by the ExcelConverter, do not modify"));
            writer.WriteLine("////////////////////////////////////////////");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#include \"CoreMinimal.h\"");
            writer.WriteLine("#include \"CommonEnumDefines.generated.h\"");
        }

        void FileHeaderTool(StreamWriter writer)
        {
            DateTime now = DateTime.Now;
            writer.WriteLine("////////////////////////////////////////////");
            writer.WriteLine(string.Format("//automatically generated by the ExcelConverter, do not modify"));
            writer.WriteLine("////////////////////////////////////////////");
            writer.WriteLine();
            writer.WriteLine("namespace ExcelConvertLib\r\n{");
        }


        void MakeEnumClass(StreamWriter writer, string section, List<EnumInfo> infos)
        {
            uint max = 0;
            foreach (EnumInfo info in infos)
            {
                max = Math.Max(max, info.Value);
            }

            if (max < 256)
            {
                sb.Append("UENUM(BlueprintType)\n");
                sb.Append(string.Format("enum class E{0} : uint8\n", section));
            }
            else
            {
                sb.Append("UENUM()\n");
                sb.Append(string.Format("enum class E{0} : uint16\n", section));
            }
            sb.Append("{\n");

            for (int i = 0; i < infos.Count; ++i)
            {
                EnumInfo info = infos[i];
                Utility.AddTab(sb, 1);
                if (i == 0 || info.Desc.Length == 0)
                {
                    sb.Append(string.Format("{0} = {1}, \n", info.Name, info.Value));
                }
                else if (info.Name[0] == '_')
                {
                    sb.Append(string.Format("{0} = {1}\tUMETA(hidden), \n", info.Name, info.Value));
                }
                else if (IsCommentEnumInfo(info))
                {
                    sb.Append(string.Format("{0}\n", info.Name));
                }
                else
                {
                    sb.Append(string.Format("{0} = {1}, \t\t//{2} \n", info.Name, info.Value, info.Desc));
                }
            }

            sb.Append("};\n"); 
            writer.WriteLine(sb.ToString()); sb.Clear();
        }

        public bool OnGenerateEnum()
        {
            // 띄워둔 상태에서 수정 후 추출할 수 있으므로 다시 로딩한다
            if (MainModule.Inst.ReadExcel(CommonDefines.ExcelFolder, ConfigSystem.Inst.EnumTable, true))
            {
                MainModule.Inst.ReadConfig();
            }
            else
                return false;
            
            MainModule.Inst.HasError = false;
            if (MainModule.Inst.CheckEnumUniqueByContentID() == false)
            {
                return false;
            }

            if (!MainModule.CheckOutClientCodeFile("CommonEnumDefines.h"))      //perforce check   
            {
                LogSystem.Inst.Add(string.Format("P4Error failed check CommonEnumDefines "));
                return false;
            }

            string output = MainModule.Inst.GetClientCodePath( "CommonEnumDefines.h");            
            if (File.Exists(output))
            {
                File.Delete(output);
            }
            StreamWriter writer = new StreamWriter(
                     new FileStream(@output, FileMode.Create, FileAccess.ReadWrite), Encoding.UTF8);

            FileHeader(writer);
            foreach (KeyValuePair<string, List<EnumInfo>> entry in MainModule.Inst.EnumDefInfos)
            {
                writer.WriteLine();
                MakeEnumClass(writer, entry.Key, entry.Value);

            }
            writer.Flush();
            writer.Close();

            LogSystem.Inst.Add(string.Format("Generate :{0} ", output));

            // Tool Use c# file
            OnGenerateEnumCheck();

            return !MainModule.Inst.HasError;
        }

        // Tool Code Generate 
        void MakeToolEnumClass(StreamWriter writer, string section, List<EnumInfo> infos)
        {
            uint max = 0;
            foreach (EnumInfo info in infos)
            {
                max = Math.Max(max, info.Value);
            }
                   
            sb.Append(string.Format("public enum {0} : int\n", section));
            sb.Append("{\n");

            for (int i = 0; i < infos.Count; ++i)
            {
                EnumInfo info = infos[i];
                Utility.AddTab(sb, 1);
                if (i == 0 || info.Desc.Length == 0)
                {
                    sb.Append(string.Format("{0} = {1}, \n", info.Name, info.Value));
                }
                else if (info.Name[0] == '_')
                {
                    //sb.Append(string.Format("{0} = {1}\tUMETA(hidden), \n", info.Name, info.Value));
                }
                else if (IsCommentEnumInfo(info))
                {
                    sb.Append(string.Format("{0}\n", info.Name));
                }
                else
                {
                    sb.Append(string.Format("{0} = {1}, \t\t//{2} \n", info.Name, info.Value, info.Desc));
                }
            }

            sb.Append("};\n");
            writer.WriteLine(sb.ToString()); sb.Clear();
        }

        public bool OnGenerateEnumCheck() // cs file generate
        {
            // 띄워둔 상태에서 수정 후 추출할 수 있으므로 다시 로딩한다
            if (MainModule.Inst.ReadExcel(CommonDefines.ExcelFolder, ConfigSystem.Inst.EnumTable, true))
            {
                MainModule.Inst.ReadConfig();
            }
            else
                return false;

            MainModule.Inst.HasError = false;

            //if (!MainModule.CheckOutToolCodeFile("CommonEnumDefines.cs"))      //perforce check   
            //{
            //    LogSystem.Inst.Add(string.Format("P4Error failed check CommonEnumDefines "));
            //    return false;
            //}
            string output = MainModule.Inst.GetToolCodePath("CommonEnumDefines.cs");
            if (File.Exists(output))
            {
                File.Delete(output);
            }
            StreamWriter writer = new StreamWriter(
                     new FileStream(@output, FileMode.Create, FileAccess.ReadWrite), Encoding.UTF8);

            FileHeaderTool(writer);
            foreach (KeyValuePair<string, List<EnumInfo>> entry in MainModule.Inst.EnumDefInfos)
            {
                writer.WriteLine();
                MakeToolEnumClass(writer, entry.Key, entry.Value);
            }
            writer.WriteLine("};");
            writer.Flush();
            writer.Close();

            LogSystem.Inst.Add(string.Format("Generate :{0} ", output));

            return !MainModule.Inst.HasError;
        }


    }
}
