using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Text;
using Excel = Microsoft.Office.Interop.Excel;

namespace ExcelConvertLib
{
    public class UETableHeaderGenerator : BaseGenerator
    {
        void FileHeader(StreamWriter writer,string tableName)
        {
            writer.WriteLine("// automatically generated by the ExcelConverter, do not modify");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#include \"Engine/DataTable.h\"");
            writer.WriteLine("#include \"FieldDefines.h\"");
            writer.WriteLine("#include \"CommonStructData.h\"");
            writer.WriteLine(string.Format("#include \"DATA_{0}.generated.h\" ", tableName));
            writer.WriteLine();
            MakeForwardDeclarations(writer);
            writer.WriteLine();
            writer.WriteLine("USTRUCT(BlueprintType)");
            writer.WriteLine(string.Format("struct F{0}Row : public FGTableRowDataBase", tableName));
            writer.WriteLine("{");
            writer.WriteLine("\tGENERATED_USTRUCT_BODY()");
            writer.WriteLine("public:");
            //writer.WriteLine(string.Format("\tF{0}Row()    ", tableName) + "{}");
            //writer.WriteLine();
        }

        void MakeForwardDeclarations(StreamWriter wirter)
        {
            HashSet<string> FowardDeclarationTypeNames = new HashSet<string>();
            foreach(var HeaderInfoData in AllHeaderInfos)
            {
                if(HeaderInfoData.clientType == EnumValueType.Undefined 
                    && HeaderInfoData.clientTypeName.Contains("*") 
                    && HeaderInfoData.clientTypeName.StartsWith("U"))
                {
                    var ClassName = HeaderInfoData.clientTypeName.Replace("*", "");
                    FowardDeclarationTypeNames.Add(ClassName);
                }
            }

            foreach(var TypeName in FowardDeclarationTypeNames)
            {
                wirter.WriteLine("class {0};", TypeName);
            }
        }

        private static string GetTypeName(HeaderInfo hInfo)
        {
            switch (hInfo.type)
            {
                // 중복 Key 가 있는 경우가 있다.
                // 일단 Key 도 코드는 생성.
                case EUsedType.Key:
                case EUsedType.common:
                case EUsedType.client:
                case EUsedType.DataName:
                    {
                        switch (hInfo.clientType)
                        {
                            case EnumValueType.ContentID:
                                {
                                    return "FContentID";
                                }
                            case EnumValueType.ObjID:
                                {
                                    return "FObjID";
                                }
                            case EnumValueType.ObjID64:
                                {
                                    return "FObjID64";
                                }
                            case EnumValueType.Properties:
                                {
                                    return "FProperties";
                                }
                            case EnumValueType.Undefined:
                                {
                                    if (hInfo.clientTypeName.StartsWith("Enum"))
                                    {
                                        return string.Format("E{0}", hInfo.clientTypeName);
                                    }
                                    return hInfo.GetClientType();
                                }
                            case EnumValueType.Range:
                                {
                                    return "FRange";
                                }
                            default:
                                {
                                    return hInfo.GetClientType();
                                }
                        }

                    }
                default:
                    break;
            }

            return string.Empty;
        }

        private static bool IsEnumType(HeaderInfo hInfo)
        {
            if(hInfo.clientType == EnumValueType.Undefined)
            { 
                if (hInfo.clientTypeName.StartsWith("E") || hInfo.clientTypeName.StartsWith("Enum"))
                {
                    return true;
                }
            }

            return false;
        }

        void MakeClassBody(StreamWriter writer)
        {
            //if (bHasContentIDKey)
            //{
            //    writer.WriteLine("\tUPROPERTY(Category=Data, EditAnywhere, BlueprintReadOnly)");
            //    writer.WriteLine("\tint64 ContentID;");
            //    writer.WriteLine();
            //}

            bool IsOnlyOneKey = KeyInfos.Count == 1;

            foreach(var hInfo in AllHeaderInfos)
            {
                if (IsOnlyOneKey && hInfo.type == EUsedType.Key)
                {
                    // 하나의 키만 사용하는 경우는 UE4 DataTable 의 RowName 으로 키 값이 들어간다.
                    // 그러므로 Struct 에서는 키 데이터를 따로 저장하지 않는다.
                    continue;
                }
                if (hInfo.bSkip)
                    continue;
                if (hInfo.type == EUsedType.memo)
                    continue;
                string TypeName = GetTypeName(hInfo);
                if (string.IsNullOrEmpty(TypeName))
                    continue;
                string VarName = hInfo.VarName;
                if (hInfo.bUseDataName && !string.IsNullOrEmpty(hInfo.CTFColumnName))
                {
                    VarName = hInfo.CTFColumnName;
                }
                else if (hInfo.bUseMerge && hInfo.CTFHeaderIndices.Count > 1)
                {
                    //TypeName = "FCondition";
                    TypeName = hInfo.clientTypeName;
                    VarName = hInfo.CTFColumnName;
                }
                //if (hInfo.type == EUsedType.DataName)
                //{
                //    writer.WriteLine("#if WITH_EDITORONLY_DATA");
                //}
                writer.WriteLine("\tUPROPERTY(Category=Data, EditAnywhere, BlueprintReadOnly)");
                writer.WriteLine("\t{0} {1};", TypeName, VarName);
                //if (hInfo.type == EUsedType.DataName)
                //{
                //    writer.WriteLine("#endif");
                //}
                writer.WriteLine();
                
            }

            // 파싱하는 함수 추가.
            writer.WriteLine("\tvirtual bool TryParse(UDataTable* InDataTable, class UDataManager* InManager) override;");
        
        }

        static private string MakeKeyTypeName(List<HeaderInfo> KeyInfos)
        {
            StringBuilder sb = new StringBuilder();

            if(KeyInfos.Count > 1)
            {
                sb.Append("TTuple<");
                for(int i=0; i<KeyInfos.Count; ++i)
                {
                    sb.AppendFormat("{0}", GetTypeName(KeyInfos[i]));
                    if(i < KeyInfos.Count-1)
                    {
                        sb.Append(",");
                    }
                }
                sb.Append(">");
            }
            else if(KeyInfos.Count > 0)
            {
                sb.Append(GetTypeName(KeyInfos[0]));
            }

            return sb.ToString();
        }

        void MakeHelperClassHeader(StreamWriter writer, string tableName)
        {
            string structClassName = string.Format("F{0}Row", tableName);
            string keyTypeName = MakeKeyTypeName(KeyInfos);
            string containerTypeName = string.Format("TMap<{0},{1}*>", keyTypeName, structClassName);
            writer.WriteLine("UCLASS()");
            writer.WriteLine("class TACTAN_API U{0}Table : public UObject", tableName);
            writer.WriteLine("{");
            writer.WriteLine("\tGENERATED_BODY()");
            writer.WriteLine("public:");
            writer.WriteLine("\tbool TryParse(UDataTable* InDataTable);");
            writer.WriteLine("");
            writer.WriteLine("\tstatic const {0}& Get{1}s(const UObject* InWorldContext);", containerTypeName, tableName);
            writer.WriteLine("\tstatic const {0}& Get{1}s(EGServiceInstanceID InInstanceID);", containerTypeName, tableName);
            {
                StringBuilder keyWithArgSb = new StringBuilder();
                for(int i =0; i<KeyInfos.Count; ++i)
                {
                    if(i > 0)
                    {
                        keyWithArgSb.Append(", ");
                    }
                    var keyInfo = KeyInfos[i];
                    keyWithArgSb.AppendFormat("const {0}& In{1}", GetTypeName(keyInfo), keyInfo.VarName);
                    
                }
                writer.WriteLine("\tstatic {0}* Find{1}(const UObject* InWorldContext, {2});", structClassName, tableName, keyWithArgSb.ToString());
                writer.WriteLine("\tstatic {0}* Find{1}(EGServiceInstanceID InInstanceID, {2});", structClassName, tableName, keyWithArgSb.ToString());
                
            }
            writer.WriteLine();
            writer.WriteLine("private:");
            writer.WriteLine("\t{0} DataContainer;", containerTypeName);
            writer.WriteLine();
            writer.WriteLine("\tUPROPERTY(Transient)");
            writer.WriteLine("\tUDataTable* DataTable;");
            writer.WriteLine("};");
            writer.WriteLine();
        }

        void OnGenerateHeaderFile(string tableName)
        {
            string fileName = string.Format("Data/DATA_{0}.h", tableName);
            string output = MainModule.Inst.GetClientCodePath(fileName);
            //string output = MainModule.Inst.GetOutPath("Code/DATA_", tableName, "h");

            MainModule.CheckOutUEFile("Source/TACTAN/Public", fileName);

            StreamWriter writer = new StreamWriter(
                     new FileStream(output, FileMode.Create, FileAccess.ReadWrite), Encoding.UTF8);

            FileHeader(writer, tableName);

            MakeClassBody(writer);

            writer.WriteLine("};");

            writer.WriteLine();

            MakeHelperClassHeader(writer, tableName);

            writer.Flush();
            writer.Close();

            LogSystem.Inst.Add(string.Format("Generate :{0} ", output));

        }

        void MakeHelperClassCpp(StreamWriter writer, string tableName)
        {
            string className = string.Format("U{0}Table", tableName);
            string structName = string.Format("F{0}Row", tableName);
            string keyTypeName = MakeKeyTypeName(KeyInfos);
            string containerTypeName = string.Format("TMap<{0},{1}*>", keyTypeName, structName);
            bool IsOnlyOneKey = KeyInfos.Count == 1;

            writer.WriteLine();
            writer.WriteLine("bool {0}::TryParse(UDataTable* InDataTable)", className);
            writer.WriteLine("{");
            writer.WriteLine("\tDataTable = InDataTable;");
            writer.WriteLine("\tDataContainer.Empty();");
            writer.WriteLine("\tif(!DataTable)");
            writer.WriteLine("\t{");
            writer.WriteLine("\t\treturn false;");
            writer.WriteLine("\t}");
            writer.WriteLine();

            writer.WriteLine("\tstatic const FString ContextString(TEXT(\"{0}\"));", className);

            writer.WriteLine("\tTArray<{0}*> TableRows;", structName);
            writer.WriteLine("\tInDataTable->GetAllRows<{0}>(ContextString, TableRows);", structName);
            writer.WriteLine("\t");
            if(IsOnlyOneKey)
            {
                // 이 경우는 RowName 을 키로 해서 처리하는 것으로 한다.
                writer.WriteLine("\tTArray<FName> KeyNames = InDataTable->GetRowNames();");
                writer.WriteLine("\tint32 Idx = 0;");
                writer.WriteLine("\tfor ({0}* It : TableRows)", structName);
                writer.WriteLine("\t{");
                if(IsEnumType(KeyInfos[0]))
                {
                    writer.WriteLine("\t\t{0} Key = static_cast<{0}>(StaticEnum<{0}>()->GetValueByName(KeyNames[Idx++]));", keyTypeName);
                    writer.WriteLine("\t\tDataContainer.Emplace(Key, It);");
                }
                else 
                {
                    writer.WriteLine("\t\t{0} Key;", keyTypeName);
                    switch(KeyInfos[0].clientType)
                    {
                        case EnumValueType.String:
                            {
                                writer.WriteLine("\t\tKey = KeyNames[Idx++].ToString();");
                            }
                            break;
                        case EnumValueType.Name:
                            {
                                writer.WriteLine("\t\tKey = KeyNames[Idx++];");
                            }
                            break;
                        default:
                            {
                                writer.WriteLine("\t\tif({0}::Parse(KeyNames[Idx++].ToString(), Key))", keyTypeName);
                            }
                            break;
                    }
                    writer.WriteLine("\t\t{");
                    writer.WriteLine("\t\t\tDataContainer.Emplace(Key, It);");
                    writer.WriteLine("\t\t}");
                }
                writer.WriteLine("\t}");
            }
            else
            {
                writer.WriteLine("\tfor ({0}* It : TableRows)", structName);
                writer.WriteLine("\t{");
                {
                    writer.Write("\t\t{0} Key = {0}(", keyTypeName);
                    for (int i = 0; i < KeyInfos.Count; ++i)
                    {
                        var keyInfo = KeyInfos[i];
                        writer.Write("It->{0}", keyInfo.VarName);
                        if (i < KeyInfos.Count - 1)
                        {
                            writer.Write(", ");
                        }
                    }
                    writer.WriteLine(");");
                }
                writer.WriteLine("\t\tDataContainer.Emplace(Key, It);");
                writer.WriteLine("\t}");
            }

            writer.WriteLine("\t");

            writer.WriteLine("\treturn true;");
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("const {0}& {2}::Get{1}s(const UObject* InWorldContext)", containerTypeName, tableName, className);
            writer.WriteLine("{");
            writer.WriteLine("\tif (UDataManager * DataManager = DATA(InWorldContext))");
            writer.WriteLine("\t{");
            writer.WriteLine("\t\tif ({0} * Table = DataManager->GetDataTableObject<{0}>())", className);
            writer.WriteLine("\t\t{");
            writer.WriteLine("\t\t\treturn Table->DataContainer;");
            writer.WriteLine("\t\t}");
            writer.WriteLine("\t}");
            writer.WriteLine();

            writer.WriteLine("\tstatic {0} Empty;", containerTypeName);
            writer.WriteLine("\treturn Empty;");
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("const {0}& {2}::Get{1}s(EGServiceInstanceID InInstanceID)", containerTypeName, tableName, className);
            writer.WriteLine("{");
            writer.WriteLine("\tif (UDataManager * DataManager = DATA(InInstanceID))");
            writer.WriteLine("\t{");
            writer.WriteLine("\t\tif ({0} * Table = DataManager->GetDataTableObject<{0}>())", className);
            writer.WriteLine("\t\t{");
            writer.WriteLine("\t\t\treturn Table->DataContainer;");
            writer.WriteLine("\t\t}");
            writer.WriteLine("\t}");
            writer.WriteLine();

            writer.WriteLine("\tstatic {0} Empty;", containerTypeName);
            writer.WriteLine("\treturn Empty;");
            writer.WriteLine("}");
            writer.WriteLine();

            StringBuilder keyWithArgSb = new StringBuilder();
            for (int i = 0; i < KeyInfos.Count; ++i)
            {
                if (i > 0)
                {
                    keyWithArgSb.Append(", ");
                }
                var keyInfo = KeyInfos[i];
                keyWithArgSb.AppendFormat("const {0}& In{1}", GetTypeName(keyInfo), keyInfo.VarName);

            }

            Action<string> findFuncWrite = (string inDataKey) => {
                writer.WriteLine("{");
                writer.WriteLine("\tif (UDataManager * DataManager = DATA({0}))", inDataKey);
                writer.WriteLine("\t{");
                writer.WriteLine("\t\tif ({0} * Table = DataManager->GetDataTableObject<{0}>())", className);
                writer.WriteLine("\t\t{");
                if (IsOnlyOneKey)
                {
                    writer.WriteLine("\t\t\tauto* It = Table->DataContainer.Find(In{0});", KeyInfos[0].VarName);
                }
                else
                {
                    writer.Write("\t\t\t{0} Key = {0}(", keyTypeName);
                    for (int i = 0; i < KeyInfos.Count; ++i)
                    {
                        var keyInfo = KeyInfos[i];
                        writer.Write("In{0}", keyInfo.VarName);
                        if (i < KeyInfos.Count - 1)
                        {
                            writer.Write(", ");
                        }
                    }
                    writer.WriteLine(");");
                    writer.WriteLine("\t\t\tauto* It = Table->DataContainer.Find(Key);");
                }
                writer.WriteLine("\t\t\tif (It)");
                writer.WriteLine("\t\t\t{");
                writer.WriteLine("\t\t\t\treturn *It;");
                writer.WriteLine("\t\t\t}");
                writer.WriteLine("\t\t}");
                writer.WriteLine("\t}");
                writer.WriteLine("\treturn nullptr;");

                writer.WriteLine("}");

            };

            writer.WriteLine("{0}* {2}::Find{1}(const UObject* InWorldContext, {3})", structName, tableName, className, keyWithArgSb.ToString());
            findFuncWrite("InWorldContext");
            writer.WriteLine("{0}* {2}::Find{1}(EGServiceInstanceID InInstanceID, {3})", structName, tableName, className, keyWithArgSb.ToString());
            findFuncWrite("InInstanceID");

            writer.WriteLine();
        }

        void OnGenerateCppFile(string tableName)
        {
            string fileName = string.Format("Data/DATA_{0}.cpp", tableName);
            string output = MainModule.Inst.GetClientCodePath(fileName);
            output = output.Replace("/Public/", "/Private/");

            MainModule.CheckOutUEFile("Source/TACTAN/Private", fileName);
            
            StreamWriter writer = new StreamWriter(
                     new FileStream(output, FileMode.Create, FileAccess.ReadWrite), Encoding.UTF8);

            writer.WriteLine("// automatically generated by the ExcelConverter, do not modify");
            writer.WriteLine();
            writer.WriteLine("#include \"Data/DATA_{0}.h\"", tableName);
            writer.WriteLine("#include \"System/DataManager.h\"");
            writer.WriteLine();

            string structName = string.Format("F{0}Row", tableName);
            string tableClassName = string.Format("U{0}Table", tableName);

            writer.WriteLine("bool {0}::TryParse(UDataTable* InDataTable, UDataManager* InManager)", structName);
            writer.WriteLine("{");
            writer.WriteLine("\t{0}* TableObject = NewObject<{0}>(InManager, FName(TEXT(\"{0}\")), RF_Transactional);", tableClassName);
            writer.WriteLine("\tif(TableObject->TryParse(InDataTable))");
            writer.WriteLine("\t{");
            writer.WriteLine("\t\tInManager->AddDataTableObject(TableObject);");
            writer.WriteLine("\t\treturn true;");
            writer.WriteLine("\t}");
            writer.WriteLine("\treturn false;");
            writer.WriteLine("}");
            writer.WriteLine();

            MakeHelperClassCpp(writer, tableName);

            writer.Flush();
            writer.Close();

            LogSystem.Inst.Add(string.Format("Generate :{0} ", output));

        }

        public override bool OnGenerate(string tableName)
        {
            if (false == CollectInfoSheet())
            {
                return false;
            }
            if (ClientFileName == "")
            {
                return true;
            }

            string[] Parsed = ClientFileName.Split('.');
            if (Parsed.Length == 0)
            {
                return false;
            }

            tableName = Parsed[0].ToUpper();
            if ( !string.IsNullOrWhiteSpace(CombineFileName))
            {
                tableName = CombineFileName.ToUpper();
            }

            ////// Header
            OnGenerateHeaderFile(tableName);

            ////// CPP
            OnGenerateCppFile(tableName);
            return true;
        }


    }
}
